### ISSUE TITLE
/me/madhead/Shyriiwook availability in lock screen

### ISSUE THREAD

**Issue by VytasLTU** [madhead/shyriiwook#12]
Hello, very nice extension - just what I was looking for recently migrated to Wayland.

However, object /me/madhead/Shyriiwook is not available when screen is locked.

script I leave running in background:

```bash
dbus-monitor --session "type='signal',interface='org.gnome.ScreenSaver'" | \
(
  while true; do
    read X
                  ### "boolean true" here runs command on locking screen, "boolean false" - on unlocking
    if echo $X | grep "boolean true" &> /dev/null; then
      gdbus call --session --dest org.gnome.Shell --object-path /me/madhead/Shyriiwook --method me.madhead.Shyriiwook.activate "lt"
    fi
  done
)
```

When I do screen locking, gdbus call produces error output:
`Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Objekto kelyje „/me/madhead/Shyriiwook“ nėra`

Localized error message saying: Object in path "/me/madhead/Shyriiwook" not found

When I modify script to run on unlocking screen (boolean false) everything works as expected - language is switched

Fedora 40
Gnome 46

**Comment by madhead** [comment]
Hey! Excuse me for ignoring it.

Well, this extension works by adding an extension to the current DBus session, which may not be available when the screen is locked?

I'll take a deeper look, though.

**Comment by madhead** [comment]
I am not an expert in GNOME / DBus, but AFAIU, the Gnome Shell object exists only in the "session" DBus, but not in the "system" DBus, which exists, I believe, globally, including the lock screens. I assume that during the lock screen, you canoot access a session.
